name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ env.SOM_VAR }}
      - run: echo ${{ env.ENV_VAR }}
      - run: echo ${{ env.PAS_VAR }}
        env:
          PAS_VAR: ${{ env.SOM_VAR }}
