name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ vars.SOM_VAR }}
      - run: echo ${{ vars.ENV_VAR }}
      - run: |
          echo ${{ env.FIR_VAR }}
          echo ${{ env.SEC_VAR }}
        env:
          FIR_VAR: ${{ vars.SOM_VAR }}
          SEC_VAR: ${{ vars.ENV_VAR }}
