name: Semantic Release
on:
  push:
    branches: ['main']
jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: actions/create-github-app-token@c1a285145b9d317df6ced56c09f525b5c2b6f755 # v1.11.1
        id: app-token
        with:
          app-id: ${{ secrets.SEMANTIC_RELEASE_GITHUB_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_GITHUB_APP_PRIVATE_KEY }}
          owner: jouzen

      - name: Create Tag and Release
        uses: cycjimmy/semantic-release-action@b1b432f13acb7768e0c8efdec416d363a57546f2 # v4.1.1
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/release-notes-generator
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
